owner: projetignis
repo: uptime

sites:
  - name: Home
    url: https://www.projetignis.fr
  - name: Vault
    url: https://vault.projetignis.fr
  - name: Mail
    url: https://mail.projetignis.fr
  - name: Git
    url: https://git.projetignis.fr
  - name: S3
    url: https://s3.projetignis.fr
  - name: Wiki
    url: https://wiki.projetignis.fr

status-website:
  cname: status.projetignis.fr
  name: Ignis
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://www.projetignis.fr
    - title: GitHub
      href: https://github.com/$OWNER
