owner: projetignis
repo: status

sites:
  - name: Alfa
    url: https://alfa.projetignis.fr
    expectedStatusCodes:
      - 404
  - name: Bravo
    url: https://bravo.projetignis.fr
    expectedStatusCodes:
      - 404
  - name: Charlie
    url: https://charlie.projetignis.fr
    expectedStatusCodes:
      - 404
  - name: Home
    url: https://www.projetignis.fr
  - name: Status
    url: https://status.projetignis.fr
  - name: Mail
    url: https://mail.projetignis.fr
  - name: Vault
    url: https://vault.projetignis.fr
  - name: Git
    url: https://git.projetignis.fr
  - name: Git (SSH)
    check: tcp-ping
    url: projetignis.fr
    port: 22
  - name: Registry
    url: https://registry.projetignis.fr
  - name: S3
    url: https://s3.projetignis.fr
    expectedStatusCodes:
      - 200
      - 401
      - 403
  - name: CDN
    url: https://cdn.projetignis.fr
    expectedStatusCodes:
      - 200
      - 401
      - 403
  - name: API
    url: https://api.projetignis.fr
  - name: Cloud
    url: https://cloud.projetignis.fr
  - name: Analytics
    url: https://analytics.projetignis.fr
  - name: Monitor
    url: https://monitor.projetignis.fr
  - name: Chat
    url: https://chat.projetignis.fr
  - name: Sentry
    url: https://sentry.projetignis.fr
  - name: Pages
    url: https://projetignis.page
    expectedStatusCodes:
      - 200
      - 302
      - 404
  - name: SMTP (25)
    check: tcp-ping
    url: mail.projetignis.fr
    port: 25
  - name: ESMTP (465)
    check: tcp-ping
    url: mail.projetignis.fr
    port: 465
  - name: ESMTP (587)
    check: tcp-ping
    url: mail.projetignis.fr
    port: 587
  - name: POP3 (110)
    check: tcp-ping
    url: mail.projetignis.fr
    port: 110
  - name: POP3 (995)
    check: tcp-ping
    url: mail.projetignis.fr
    port: 995
  - name: IMAP4 (143)
    check: tcp-ping
    url: mail.projetignis.fr
    port: 143
  - name: IMAP4 (993)
    check: tcp-ping
    url: mail.projetignis.fr
    port: 993
    
status-website:
  cname: status.projetignis.fr
  name: Ignis
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://www.projetignis.fr
    - title: GitHub
      href: https://github.com/$OWNER
